apiVersion: apps/v1
kind: Deployment
metadata:
  name: commits-tracking-system
  labels:
    app: commits-tracking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commits-tracking-system
  template:
    metadata:
      labels:
        app: commits-tracking-system
    spec:
      containers:
        - name: commits-tracking-system
          image: gcr.io/iitcloudcw/commits-tracking-system:prod  # Replace with your Docker Hub image and tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/commits-tracking-system/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/v1/commits-tracking-system/actuator/health
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: "300m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
