server:
  port: 9091

github:
  user-detail-url: https://api.github.com/repos/EthicalML/awesome-production-machine-learning/contributors

spring:
  data:
    mongodb:
      uri: mongodb+srv://hiranjanperera7532:xxBcZHIuBBZhoAwL@iit-cluster.ea0cis1.mongodb.net/Dev-IQ-Tracker