server:
  port: 8080
  servlet:
    context-path: /api/v1/commits-tracking-system

github:
  commits-detail-url: https://api.github.com/repos/barchart/marketdata-api-js/contributors


spring:
  data:
    mongodb:
      uri: mongodb+srv://hiranjan20231914:Clfyr9SCLLNSrNhg@iitcloud.fjpgsya.mongodb.net/Dev-IQ-Tracker