server:
  port: 9091

github:
  commits-detail-url: https://api.github.com/repos/barchart/marketdata-api-js/contributors

spring:
  data:
    mongodb:
      uri: mongodb+srv://hiranjanperera7532:xxBcZHIuBBZhoAwL@iit-cluster.ea0cis1.mongodb.net/Dev-IQ-Tracker